a1 = (input('Digita alguma coisa: '))
a2 = (input('Digita alguma coisa denovo: '))
s = a1 + a2
print("só letras maiúsculas?",s.isupper())
print("letras e/ou números?",s.isalnum())
print("só letras?",s.isalpha())
print("só caracteres ASCII?",s.isascii())
print("só números decimais (0–9)?",s.isdecimal())
print("só dígitos numéricos?",s.isdigit())
print("nome válido de variável?",s.isidentifier())
print("só letras minúsculas?",s.islower())
print("caracteres numéricos?",s.isnumeric())
print("pode ser exibido na tela?",s.isprintable())
print("só espaços?",s.isspace())
print("formato de título?",s.istitle())